languaje: java
script: mvn clean test
notifications:
  slack:
    on_success: change
  email:
    recipients:
      - jescobarlasalas@alumno.unlam.edu.ar

    on_success: change 
    on_failure: always 
jdk:
  - openjdk11